# Spécifier la version à utiliser
version: '3'

# Détailler les différents services (images)
services:
    php-apache:                                         # Nom du service (arbitraire)
        #image: php:7.2.1-apache                        # Le nom de l'image pour ce service (dans le cas ou on se refére à l'original)

        build:
            context: ./php-apache                       # Chemin pointant vers le containeur
        ports:
            - 8002:80                                     # Le port dédié à ce service         
        volumes:
            - ./DocumentRoot:/var/www/html              # Les fichiers local:(vers)images
        links:
            - 'mariadb'                                 # Definis la dependance(qui sera lancé en premiére) de l'image

    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql                    # Volume nomé vers le point de montage du containeur
        environment:                                    # Definir les variable d'environement qui influenceront le comportement de notre containeur
            TZ: "Europe/Brussels"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "tulesaispas"
            MYSQL_USER: 'charlene'
            MYSQL_PASSWORD: 'tulesaispas'
            MYSQL_DATABASE: 'testdb'
    
volumes:                                                # Definir le volume nomé référencer dans le service mariadb
    mariadb: